package JFrames;

import BD.BaseDatos;
import BD.Mensajes;
import static JFrames.Login.mandar;
import static JFrames.Muro.recibo;
import static JFrames.Muro.reciboName;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Antonio
 */
public class MessageCreate extends javax.swing.JFrame {

    /**
     * Creates new form MessageCreate
     */
    
    public MessageCreate() {
        initComponents();
        this.setTitle("Escribir mensaje");
        lblemail.setVisible(false);
        lblemail.setText(recibo);//email from
        lblnombre.setText(reciboName);//nombre
        lblnombreEnvia.setText(mandar);//email to
        lblnombreEnvia.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBentrada = new javax.swing.JPanel();
        txtescribonombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtTexto = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblnombreEnvia = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtasunto1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBentrada.setBackground(new java.awt.Color(44, 47, 51));
        panelBentrada.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        panelBentrada.setPreferredSize(new java.awt.Dimension(600, 600));
        panelBentrada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtescribonombre.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtescribonombre.setForeground(new java.awt.Color(0, 0, 0));
        txtescribonombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtescribonombreActionPerformed(evt);
            }
        });
        panelBentrada.add(txtescribonombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 80, 284, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Asunto");
        panelBentrada.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 128, 48, -1));

        btnEnviar.setBackground(new java.awt.Color(0, 0, 0));
        btnEnviar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        panelBentrada.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 434, 116, 32));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelBentrada.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 434, 116, 32));

        txtTexto.setColumns(20);
        txtTexto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTexto.setRows(5);
        txtTexto.setToolTipText("");
        panelBentrada.add(txtTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 156, 518, 260));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/iconos45x45/logo(1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBentrada.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 0, -1, -1));
        panelBentrada.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 6, 265, -1));

        lblemail.setBackground(new java.awt.Color(44, 47, 51));
        lblemail.setForeground(new java.awt.Color(255, 255, 255));
        lblemail.setOpaque(true);
        panelBentrada.add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 6, 131, 26));

        lblnombre.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(255, 255, 255));
        panelBentrada.add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 283, 30));

        lblnombreEnvia.setBackground(new java.awt.Color(44, 47, 51));
        lblnombreEnvia.setForeground(new java.awt.Color(255, 255, 255));
        lblnombreEnvia.setOpaque(true);
        panelBentrada.add(lblnombreEnvia, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 6, 131, 26));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("de");
        panelBentrada.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 85, 48, -1));

        txtasunto1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtasunto1.setForeground(new java.awt.Color(0, 0, 0));
        txtasunto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtasunto1ActionPerformed(evt);
            }
        });
        panelBentrada.add(txtasunto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 123, 284, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("para");
        panelBentrada.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 83, 38, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelBentrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelBentrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtescribonombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtescribonombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtescribonombreActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        BaseDatos bd = new BaseDatos();
        Mensajes men = new Mensajes();

        if (txtescribonombre.getText().equals("")
                || txtTexto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios, debe rellenar todos los campos");
        } else {
            if (bd.mensajes(men)) {
                
                men.setName(txtescribonombre.getText());
                men.setAsunto(txtasunto1.getText());
                men.setTexto(txtTexto.getText());
                men.setEmail(recibo);
                men.setEnvemail(mandar);

                JOptionPane.showMessageDialog(null, "Mensaje enviado correctamente");
                bd.mensajes(men);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Mensaje no enviado intentelo de nuevo");
            }

        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void txtasunto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtasunto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtasunto1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessageCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessageCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessageCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessageCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MessageCreate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblnombreEnvia;
    private javax.swing.JPanel panelBentrada;
    private javax.swing.JTextArea txtTexto;
    private javax.swing.JTextField txtasunto1;
    private javax.swing.JTextField txtescribonombre;
    // End of variables declaration//GEN-END:variables
}
